### ISSUE TITLE
Server error 500 when clicking on production support tab 

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#672]
**Describe the bug**
I'm trying to address support tickets by accessing the support item in the  menu on the left. 

![Screenshot 2024-03-25 at 22 45 25](https://github.com/eyra/mono/assets/88683839/73450b70-adc3-414b-abf5-cfa40ec488a7)

I discovered this issue in production by accident and can reproduce it in next.dev.eyra.co

**To Reproduce**
1. Login using your eyra admin google account /admin/login
1. Create a support ticket (as an admin?)
2. visit /support/ticket (click on support in the menu)
3. Wait a bit (can take 20+ seconds)
4. internal server error 

**Expected behavior**
- An overview of tickets that I can select and reply to / close 

**Screenshots**
from dev environment

![Screenshot 2024-03-25 at 22 52 06](https://github.com/eyra/mono/assets/88683839/72882f2b-3a18-4220-a4f5-db2304d90455)

**Desktop (please complete the following information):**
mac safari

**Comment by TjerkNan** [comment]
I can still reproduce this issue, although the difference is that I get the error when I click on the support ticket. 

https://github.com/eyra/mono/assets/88683839/befd284b-d5ff-411e-9c7b-3ee971ecf5e3


```
{"time":"2024-04-22T19:05:52.467Z","severity":"error","message":"an exception was raised:\n    ** (FunctionClauseError) no function clause matching in Systems.Support.TicketPage.to_member/1\n        (core 0.1.0) systems/support/ticket_page.ex:40: Systems.Support.TicketPage.to_member(%Systems.Support.TicketModel{__meta__: #Ecto.Schema.Metadata<:loaded, \"helpdesk_tickets\">, id: 1, user_id: 24, user: #Core.Accounts.User<__meta__: #Ecto.Schema.Metadata<:loaded, \"users\">, id: 24, email: \"a.m.mendrik@gmail.com\", hashed_password: \"$2b$12$3bv.Ykm6uwVKZ66/Cy0JD.Q5oiwPqfeSHC4Q7UgJZxR3rRF35VGn2\", confirmed_at: ~N[2024-01-18 09:00:59], displayname: nil, visited_pages: nil, researcher: true, student: nil, coordinator: nil, profile: %Core.Accounts.Profile{__meta__: #Ecto.Schema.Metadata<:loaded, \"user_profiles\">, id: 64, fullname: nil, title: nil, photo_url: nil, user_id: 24, user: #Ecto.Association.NotLoaded<association :user is not loaded>, inserted_at: ~N[2024-03-31 19:07:58], updated_at: ~N[2024-03-31 19:07:58]}, features: nil, inserted_at: ~N[2024-01-18 08:59:23], updated_at: ~N[2024-01-18 09:00:59], ...>, type: :question, description: \"test\", title: \"Test\", completed_at: nil, inserted_at: ~N[2024-01-18 10:44:11], updated_at: ~N[2024-01-18 10:44:11]})\n        (core 0.1.0) systems/support/ticket_page.ex:37: Systems.Support.TicketPage.update_member/1\n        (core 0.1.0) systems/support/ticket_page.ex:30: Systems.Support.TicketPage.\"mount (overridable 1)\"/3\n        (phoenix_live_view 0.20.1) lib/phoenix_live_view/utils.ex:394: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5\n        (telemetry 1.2.1) /home/runner/work/mono/mono/core/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3\n        (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:1127: Phoenix.LiveView.Channel.verified_mount/8\n        (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:84: Phoenix.LiveView.Channel.handle_info/2\n        (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4","metadata":{"domain":["elixir"],"erl_level":"error"}}


```

**Comment by emielvdveen** [comment]
That is a different exception. Should be fixed but is not part of the original hotfix

**Comment by TjerkNan** [comment]
I will create a new issue and close this issue as soon as I've create the new iissue.
