### ISSUE TITLE
[Leaderboard] does not accept format output by benchmark script (output)

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#771]
**Describe the bug**
file contains generated example data and last newline is removed. 
This data was not accepted by the leaderboard upload. 
[
[generated-data.csv](https://github.com/eyra/mono/files/15049837/generated-data.csv)
](url)

Error message from grafana:

```
{"time":"2024-04-20T23:49:02.088Z","severity":"error","message":"GenServer #PID<0.8946.1> terminating\n** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of a float\n\n    :erlang.binary_to_float(\"success\")\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:127: anonymous fn/1 in Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/map.ex:883: Map.update!/3\n    (elixir 1.14.0) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:124: Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/stream.ex:612: anonymous fn/4 in Stream.map/2\n    (elixir 1.14.0) lib/enum.ex:4751: Enumerable.List.reduce/3\n    (elixir 1.14.0) lib/stream.ex:1811: Enumerable.Stream.do_each/4\nLast message: %Phoenix.Socket.Message{topic: \"lv:phx-F8gaxoFJNqZRh4LB\", event: \"event\", payload: %{\"cid\" => 6, \"event\" => \"process\", \"type\" => \"click\", \"value\" => %{\"item\" => \"\"}}, ref: \"140\", join_ref: \"131\"}","metadata":{"domain":["otp"],"erl_level":"error","error":{"initial_call":null,"reason":"** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of a float\n\n    :erlang.binary_to_float(\"success\")\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:127: anonymous fn/1 in Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/map.ex:883: Map.update!/3\n    (elixir 1.14.0) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:124: Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/stream.ex:612: anonymous fn/4 in Stream.map/2\n    (elixir 1.14.0) lib/enum.ex:4751: Enumerable.List.reduce/3\n    (elixir 1.14.0) lib/stream.ex:1811: Enumerable.Stream.do_each/4\n"},"error_logger":{"report_cb":"&:gen_server.format_log/1","tag":"error"}}}
```

For now this issue is just to share info. Also attached actual raw file straight from Jeroen's script.

[defiledieikmoethebben.csv](https://github.com/eyra/mono/files/15049841/defiledieikmoethebben.csv)

**Comment by TjerkNan** [comment]
@emielvdveen Ik was in staat zondag avond om die output wel op DEV in te laden en ging goed

**Comment by emielvdveen** [comment]
@TjerkNan deze heb ik op done gezet

**Comment by AdrienneMendrik** [comment]
Done
