### ISSUE TITLE
[Leaderboard] File import can't deal with empty values

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#777]
**Describe the bug**
Imported CSV lines must include float values or errors happen and the file is not imported:

```
{"time":"2024-04-23T21:26:59.630Z","severity":"error","message":"GenServer #PID<0.16540.0> terminating\n** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of a float\n\n    :erlang.binary_to_float(\"\")\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:127: anonymous fn/1 in Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/map.ex:883: Map.update!/3\n    (elixir 1.14.0) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:124: Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/stream.ex:612: anonymous fn/4 in Stream.map/2\n    (elixir 1.14.0) lib/enum.ex:4751: Enumerable.List.reduce/3\n    (elixir 1.14.0) lib/stream.ex:1811: Enumerable.Stream.do_each/4\nLast message: %Phoenix.Socket.Message{topic: \"lv:phx-F8j8xb9J-NUGEjgR\", event: \"event\", payload: %{\"cid\" => 6, \"event\" => \"process\", \"type\" => \"click\", \"value\" => %{\"item\" => \"\"}}, ref: \"193\", join_ref: \"184\"}","metadata":{"domain":["otp"],"erl_level":"error","error":{"initial_call":null,"reason":"** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of a float\n\n    :erlang.binary_to_float(\"\")\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:127: anonymous fn/1 in Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/map.ex:883: Map.update!/3\n    (elixir 1.14.0) lib/enum.ex:2468: Enum.\"-reduce/3-lists^foldl/2-0-\"/3\n    (core 0.1.0) systems/graphite/scores_parse_result.ex:124: Systems.Graphite.ScoresParseResult.convert_floats/2\n    (elixir 1.14.0) lib/stream.ex:612: anonymous fn/4 in Stream.map/2\n    (elixir 1.14.0) lib/enum.ex:4751: Enumerable.List.reduce/3\n    (elixir 1.14.0) lib/stream.ex:1811: Enumerable.Stream.do_each/4\n"},"error_logger":{"report_cb":"&:gen_server.format_log/1","tag":"error"}}}
```

**To Reproduce**
Use the code below as an example, just change the IDs to match existing submissions.

Valid
```
984,git@github.com:eyra/mono.git,07e23ce01ac00171129266e7beeb20cf81a4e793,success,,0.17,23.1,94.62,42.44
```
Not valid
```
984,git@github.com:eyra/mono.git,07e23ce01ac00171129266e7beeb20cf81a4e793,success,,0.17,23.1,94.62,
984,git@github.com:eyra/mono.git,07e23ce01ac00171129266e7beeb20cf81a4e793,success,,0.17,23.1,94.62,0
```

**Expected behavior**
The app deals with integers or None values.

**Comment by emielvdveen** [comment]
@TjerkNan does the runner return with empty values as output? Or is this a manual test?

**Comment by louwrentius** [comment]
Yes, Jeroen's benchmark script outputs empty values as output, not floats 0.0 or something.

**Comment by TjerkNan** [comment]
Met meerdere leaderboards bevestigd dat dit goed gaat
