### ISSUE TITLE
Unhandled signal error when uploading zip for benchmark (upload failed)

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#832]
**Describe the bug**

Benchmark upload of zip for participants to download. After selecting and uploading the zip file, nothing happens and error below shows up in logs.

```
Jun 05 20:26:40 ec2-web-dev-01 core[15108]: {"time":"2024-06-05T20:26:40.327Z","severity":"error","message":"Unhandeld signal: {:instruction_tool, :update} => [:content_file,:content_page,:from_pid,:instruction_asset,:instruction_page,:instruction_tool], FROM: #PID<0.6843.0>","metadata":{"domain":["elixir"],"erl_level":"error"}}

```

After the upload test, the server starts to keep sending out these logs:

```
Jun 05 20:49:17 ec2-web-dev-01 core[15108]: {"time":"2024-06-05T20:49:17.978Z","severity":"error","message":"GenServer #PID<0.14353.0> terminating\n** (FunctionClauseError) no function clause matching in Systems.Instruction.ForkForm.handle_event/3\n    (core 0.1.0) systems/instruction/fork_form.ex:48: Systems.Instruction.ForkForm.handle_event(\"change\", %{\"_target\" => [\"radio-group\"], \"radio-group\" => \"on\"}, #Phoenix.LiveView.Socket<id: \"phx-F9Yt3Yn5q5-hzwCS\", endpoint: CoreWeb.Endpoint, view: Systems.Assignment.ContentPage, parent_pid: nil, root_pid: #PID<0.14353.0>, router: CoreWeb.Router, assigns: %{__changed__: %{}, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Systems.Content.RepositoryModel<>, valid?: true>, flash: %{}, id: \"item_cell_213->system->#PID<0.14353.0>_tool_form\", myself: %Phoenix.LiveComponent.CID{cid: 26}, page: nil, repository: %Systems.Content.RepositoryModel{__meta__: #Ecto.Schema.Metadata<:built, \"content_repositories\">, id: nil, platform: nil, url: nil, inserted_at: nil, updated_at: nil}, tool: %Systems.Instruction.ToolModel{__meta__: #Ecto.Schema.Metadata<:loaded, \"instruction_tools\">, id: 40, auth_node_id: 2612, auth_node: %Core.Authorization.Node{__meta__: #Ecto.Schema.Metadata<:loaded, \"authorization_nodes\">, id: 2612, parent_id: 2611, parent: #Ecto.Association.NotLoaded<association :parent is not loaded>, children: #Ecto.Association.NotLoaded<association :children is not loaded>, role_assignments: #Ecto.Association.NotLoaded<association :role_assignments is not loaded>, inserted_at: ~N[2024-06-05 18:31:17], updated_at: ~N[2024-06-05 18:31:17]}, assets: [], pages: [], tool_ref: #Ecto.Association.NotLoaded<association :tool_ref is not loaded>, inserted_at: ~N[2024-06-05 18:31:17], updated_at: ~N[2024-06-05 18:31:17]}}, transport_pid: #PID<0.4292.0>, ...>)\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:716: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4\n    (telemetry 1.2.1) /home/runner/work/mono/mono/core/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:639: Phoenix.LiveView.Channel.component_handle_event/6\n    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4\n    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6\n    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\nLast message: %Phoenix.Socket.Message{topic: \"lv:phx-F9Yt3Yn5q5-hzwCS\", event: \"event\", payload: %{\"cid\" => 26, \"event\" => \"change\", \"type\" => \"form\", \"uploads\" => %{}, \"value\" => \"radio-group=on&_target=radio-group\"}, ref: \"2895\", join_ref: \"2892\"}","metadata":{"domain":["otp"],"erl_level":"error","error":{"initial_call":null,"reason":"** (FunctionClauseError) no function clause matching in Systems.Instruction.ForkForm.handle_event/3\n    (core 0.1.0) systems/instruction/fork_form.ex:48: Systems.Instruction.ForkForm.handle_event(\"change\", %{\"_target\" => [\"radio-group\"], \"radio-group\" => \"on\"}, #Phoenix.LiveView.Socket<id: \"phx-F9Yt3Yn5q5-hzwCS\", endpoint: CoreWeb.Endpoint, view: Systems.Assignment.ContentPage, parent_pid: nil, root_pid: #PID<0.14353.0>, router: CoreWeb.Router, assigns: %{__changed__: %{}, changeset: #Ecto.Changeset<action: nil, changes: %{}, errors: [], data: #Systems.Content.RepositoryModel<>, valid?: true>, flash: %{}, id: \"item_cell_213->system->#PID<0.14353.0>_tool_form\", myself: %Phoenix.LiveComponent.CID{cid: 26}, page: nil, repository: %Systems.Content.RepositoryModel{__meta__: #Ecto.Schema.Metadata<:built, \"content_repositories\">, id: nil, platform: nil, url: nil, inserted_at: nil, updated_at: nil}, tool: %Systems.Instruction.ToolModel{__meta__: #Ecto.Schema.Metadata<:loaded, \"instruction_tools\">, id: 40, auth_node_id: 2612, auth_node: %Core.Authorization.Node{__meta__: #Ecto.Schema.Metadata<:loaded, \"authorization_nodes\">, id: 2612, parent_id: 2611, parent: #Ecto.Association.NotLoaded<association :parent is not loaded>, children: #Ecto.Association.NotLoaded<association :children is not loaded>, role_assignments: #Ecto.Association.NotLoaded<association :role_assignments is not loaded>, inserted_at: ~N[2024-06-05 18:31:17], updated_at: ~N[2024-06-05 18:31:17]}, assets: [], pages: [], tool_ref: #Ecto.Association.NotLoaded<association :tool_ref is not loaded>, inserted_at: ~N[2024-06-05 18:31:17], updated_at: ~N[2024-06-05 18:31:17]}}, transport_pid: #PID<0.4292.0>, ...>)\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:716: anonymous fn/4 in Phoenix.LiveView.Channel.inner_component_handle_event/4\n    (telemetry 1.2.1) /home/runner/work/mono/mono/core/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/diff.ex:204: Phoenix.LiveView.Diff.write_component/4\n    (phoenix_live_view 0.20.1) lib/phoenix_live_view/channel.ex:639: Phoenix.LiveView.Channel.component_handle_event/6\n    (stdlib 4.0.1) gen_server.erl:1120: :gen_server.try_dispatch/4\n    (stdlib 4.0.1) gen_server.erl:1197: :gen_server.handle_msg/6\n    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\n"},"error_logger":{"report_cb":"&:gen_server.format_log/1","tag":"error"}}}
```

The actual upload seems to work when the benchmark is viewed in 'preview' mode. 
So the form page where the participant workflow is created is just not updated.
All fields entered in this workflow screen is never displayed in preview mode. 

If you keep fidling with the fields in the workflow mode the values will be saved eventually and shown in preview mode. 

**To Reproduce**
1. Create new benchmark study
2. Skip first settings page
3. Go to next page and just upload zip file

**Expected behavior**
Zip upload succeeds and no errors. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - macos safari

**Comment by TjerkNan** [comment]
Upload works instantly, is now ok.
