### ISSUE TITLE
Adding invalid input to callback url results in internal server error 500

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#854]
**Describe the bug**

An internal server error is shown when placing incorrect data into the URL at various locations. 

**To Reproduce**

Incorrect data can be a string like 'wfoeifnwoifaf'

```
A https://next.dev.eyra.co/assignment/<incorrect data>/invite
B https://next.dev.eyra.co/assignment/<incorrect data>
C https://next.dev.eyra.co/assignment/callback/<incorrect data>
```

**Expected behavior**
404 or 403 something like that.

**Screenshots**
A
```
"error","message":"#PID<0.12184.1> running CoreWeb.Endpoint (connection #PID<0.12183.1>, stream id 1) terminated\nServer: next.dev.eyra.co:80 (http)\nRequest: GET /assignment/wefwefwef23f\n** (exit) an exception was raised:\n    ** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of an integer\n\n        :erlang.binary_to_integer(\"wefwefwef23f\")\n        (core 0.1.0) systems/assignment/crew_page.ex:19: Systems.Assignment.CrewPage.get_authorization_context/3\n        (core 0.1.0) systems/assignment/crew_page.ex:1: Systems.Assignment.CrewPage.access_allowed?/3\n        (core 0.1.0) systems/assignment/crew_page.ex:1: Systems.Assignment.CrewPage.\"mount (overridable 7)\"/3\n    
```

B
```
core[29409]: {"time":"2024-06-10T21:45:47.118Z","severity":"error","message":"#PID<0.12496.1> running CoreWeb.Endpoint (connection #PID<0.12495.1>, stream id 1) terminated\nServer: next.dev.eyra.co:80 (http)\nRequest: GET /assignment/sdfwefaf\n** (exit) an exception was raised:\n    ** (ArgumentError) errors were found at the given arguments:\n\n  * 1st argument: not a textual representation of an integer\n\n        :erlang.binary_to_integer(\"sdfwefaf\")\n        (
```

C
```
core[29409]: warning: conflicting layouts found. A layout has been set with format, such as:
core[29409]:     put_layout(conn, html: {CoreWeb.Layouts, :app})
core[29409]: But also without format:
core[29409]:     put_layout(conn, {CoreWeb.Layouts, :error})
core[29409]: In this case, the layout without format will always win.
core[29409]: If you use layouts with formats, make sure that they are
core[29409]: used everywhere. Also remember to configure your controller
core[29409]: to use layouts with formats:
core[29409]:     use Phoenix.Controller, layouts: [html: {CoreWeb.Layouts, :app}]
core[29409]:   (phoenix 1.7.2) lib/phoenix/controller.ex:1038: Phoenix.Controller.assigns_layout/3
core[29409]:   (phoenix 1.7.2) lib/phoenix/controller.ex:1018: Phoenix.Controller.prepare_assigns/4
core[29409]:   (phoenix 1.7.2) lib/phoenix/controller.ex:975: Phoenix.Controller.render_and_send/4
core[29409]:   (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:84: Phoenix.Endpoint.RenderErrors.instrument_render_and_send/5
core[29409]:   (phoenix 1.7.2) lib/phoenix/endpoint/render_errors.ex:62: Phoenix.Endpoint.RenderErrors.__catch__/5
core[29409]:   (plug_cowboy 2.6.1) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
```

**Desktop (please complete the following information):**
 - Safari

**Comment by mellelieuwes** [comment]
Needs triage, new ticket is created in Basecamp
