### ISSUE TITLE
Data donation on Yoda storage backend results in no data donated on Yoda

### ISSUE THREAD

**Issue by TjerkNan** [eyra/mono#928]
**Describe the bug**
After donating data on Yoda storage, no data is stored on Yoda.

```
{"time":"2024-07-17T21:58:37.207Z","severity":"error","message":"** (FunctionClauseError) no function clause matching in Systems.Storage.Yoda.Backend.store/3\n    (core 0.1.0) systems/storage/yoda/backend.ex:8: Systems.Storage.Yoda.Backend.store(%{\"password\" => \"SUPERSECRETPASS\", \"url\" => \"URLENDINGWITHWINTERCABBAGE\", \"user\" => \"REDACTED@REDACTED.REDACTED\"}, \"[{\\\"zip_content\\\":[{\\\"filename\\\":\\\"favicon.ico\\\",\\\"compressed size\\\":\\\"3443\\\",\\\"size\\\":\\\"3870\\\"},{\\\"filename\\\":\\\"index.html\\\",\\\"compressed size\\\":\\\"358\\\",\\\"size\\\":\\\"648\\\"},{\\\"filename\\\":\\\"styles.css\\\",\\\"compressed size\\\":\\\"2939\\\",\\\"size\\\":\\\"11716\\\"},{\\\"filename\\\":\\\"logo512.png\\\",\\\"compressed size\\\":\\\"9642\\\",\\\"size\\\":\\\"9664\\\"},{\\\"filename\\\":\\\"port-0.0.0.tar.gz\\\",\\\"compressed size\\\":\\\"3615\\\",\\\"size\\\":\\\"3615\\\"},{\\\"filename\\\":\\\"asset-manifest.json\\\",\\\"compressed size\\\":\\\"1043\\\",\\\"size\\\":\\\"4205\\\"},{\\\"filename\\\":\\\"static/\\\",\\\"compressed size\\\":\\\"0\\\",\\\"size\\\":\\\"0\\\"},{\\\"filename\\\":\\\"static/css/\\\",\\\"compressed size\\\":\\\"0\\\",\\\"size\\\":\\\"0\\\"},{\\\"filename\\\":\\\"static/css/main.7a175c0d.css\\\",\\\"compressed size\\\":\\\"3650\\\",\\\"size\\\":\\\"14811\\\"},{\\\"filename\\\":\\\"static/css/main.7a175c0d.css.map\\\",\\\"compressed size\\\":\\\"1060\\\",\\\"size\\\":\\\"7388\\\"},{\\\"filename\\\":\\\"static/js/\\\",\\\"compressed size\\\":\\\"0\\\",\\\"size\\\":\\\"0\\\"},{\\\"filename\\\":\\\"static/js/main.e9161841.js.map\\\",\\\"compressed size\\\":\\\"538135\\\",\\\"size\\\":\\\"2269178\\\"},{\\\"filename\\\":\\\"static/js/main.e9161841.js.LICENSE.txt\\\",\\\"compressed size\\\":\\\"463\\\",\\\"size\\\":\\\"1528\\\"},{\\\"filename\\\":\\\"static/js/main.e9161841.js\\\",\\\"compressed size\\\":\\\"155662\\\",\\\"size\\\":\\\"550979\\\"},{\\\"filename\\\":\\\"static/media/\\\",\\\"compressed size\\\":\\\"0\\\",\\\"size\\\":\\\"0\\\"},{\\\"filename\\\":\\\"static/media/check.62d1e3846cf9f4002c37c986555f222e.svg\\\",\\\"compressed size\\\":\\\"133\\\",\\\"size\\\":\\\"187\\\"},{\\\"filename\\\":\\\"static/media/Finador-Light.494ccb1e2089d12719df.woff2\\\",\\\"compressed size\\\":\\\"60241\\\",\\\"size\\\":\\\"60236\\\"},{\\\"filename\\\":\\\"static/media/Finador-Black.b67b8620a2b660ffb525.woff2\\\",\\\"compressed size\\\":\\\"62840\\\",\\\"size\\\":\\\"62832\\\"},{\\\"filename\\\":\\\"static/media/Finador-BlackOblique.8e3feb4617564028ac09.woff\\\",\\\"compressed size\\\":\\\"73089\\\",\\\"size\\\":\\\"73116\\\"},{\\\"filename\\\":\\\"static/media/Finador-Medium.904b493a957de121d1f7.woff2\\\",\\\"compressed size\\\":\\\"55597\\\",\\\"size\\\":\\\"55592\\\"},{\\\"filename\\\":\\\"static/media/radio_active.c0fc948096ad99ce42251580aa8fd219.svg\\\",\\\"compressed size\\\":\\\"141\\\",\\\"size\\\":\\\"217\\\"},{\\\"filename\\\":\\\"static/media/Finador-LightOblique.3e4bf52dd453804f5c5a.woff\\\",\\\"compressed size\\\":\\\"72691\\\",\\\"size\\\":\\\"72692\\\"},{\\\"filename\\\":\\\"static/media/Finador-Medium.50eaf66efcc9b04bdacb.woff\\\",\\\"compressed size\\\":\\\"58524\\\",\\\"size\\\":\\\"58528\\\"},{\\\"filename\\\":\\\"static/media/Finador-Bold.e71ffcb972d66e7b1153.woff\\\",\\\"compressed size\\\":\\\"64201\\\",\\\"size\\\":\\\"64228\\\"},{\\\"filename\\\":\\\"static/media/Finador-ExtraLightOblique.e8ab73dc829840f63b79.woff2\\\",\\\"compressed size\\\":\\\"68109\\\",\\\"size\\\":\\\"68120\\\"},{\\\"filename\\\":\\\"static/media/Finador-ExtraLight.014fc2b20374c524c007.woff2\\\",\\\"compressed size\\\":\\\"60096\\\",\\\"size\\\":\\\"60104\\\"},{\\\"filename\\\":\\\"static/media/Finador-Thin.6529a0517644d0d94527.woff\\\",\\\"compressed size\\\":\\\"55814\\\",\\\"size\\\":\\\"55824\\\"},{\\\"filename\\\":\\\"static/media/undo.7711178100058d5fe1926827dfdd12d6.svg\\\",\\\"compressed size\\\":\\\"207\\\",\\\"size\\\":\\\"357\\\"},{\\\"filename\\\":\\\"static/media/Finador-RegularOblique.f7c72e2eb5fd6458bd52.woff2\\\",\\\"compressed size\\\":\\\"68755\\\",\\\"size\\\":\\\"68740\\\"},{\\\"filename\\\":\\\"static/media/delete.52e6851b1a65c25db5a603cd9988d336.svg\\\",\\\"compressed size\\\":\\\"302\\\",\\\"size\\\":\\\"709\\\"},{\\\"filename\\\":\\\"static/media/Finador-MediumOblique.bf6a6e7c7e9e2a0292e7.woff\\\",\\\"compressed size\\\":\\\"66166\\\",\\\"size\\\":\\\"66168\\\"},{\\\"filename\\\":\\\"static/media/back.da58add26f133b17074fc3c8bc19b1d4.svg\\\",\\\"compressed size\\\":\\\"150\\\",\\\"size\\\":\\\"190\\\"},{\\\"filename\\\":\\\"static/media/Finador-Light.96c536418fb8c38ab8ae.woff\\\",\\\"compressed size\\\":\\\"63195\\\",\\\"size\\\":\\\"63196\\\"},{\\\"filename\\\":\\\"static/media/Finador-RegularOblique.66b1b40866f3f75015d6.woff\\\",\\\"compressed size\\\":\\\"73107\\\",\\\"size\\\":\\\"73100\\\"},{\\\"filename\\\":\\\"static/media/Finador-Bold.334ed1b8ee1f33e07748.woff2\\\",\\\"compressed size\\\":\\\"60706\\\",\\\"size\\\":\\\"60732\\\"},{\\\"filename\\\":\\\"static/media/Finador-ThinOblique.b60ea6bcee952536addf.woff2\\\",\\\"compressed size\\\":\\\"59462\\\",\\\"size\\\":\\\"59452\\\"},{\\\"filename\\\":\\\"static/media/py_worker.4d565c1e3776ff5802dd.js\\\",\\\"compressed size\\\":\\\"839\\\",\\\"size\\\":\\\"2059\\\"},{\\\"filename\\\":\\\"static/media/Finador-ExtraLight.1a0a300e2b52e80d1225.woff\\\",\\\"compressed size\\\":\\\"63038\\\",\\\"size\\\":\\\"63052\\\"},{\\\"filename\\\":\\\"static/media/Finador-BlackOblique.e323533438b6a57d310a.woff2\\\",\\\"compressed size\\\":\\\"68787\\\",\\\"size\\\":\\\"68772\\\"},{\\\"filename\\\":\\\"static/media/check_active.960826e06093589f13a939cd11c7a1af.svg\\\",\\\"compressed size\\\":\\\"248\\\",\\\"size\\\":\\\"413\\\"},{\\\"filename\\\":\\\"static/media/Finador-BoldOblique.bd01aa239f47f4decca1.woff2\\\",\\\"compressed size\\\":\\\"67103\\\",\\\"size\\\":\\\"67088\\\"},{\\\"filename\\\":\\\"static/media/Finador-LightOblique.19443e16a508859dc3e6.woff2\\\",\" <> ..., %{\"identifier\" => [[\"assignment\", 191], [\"task\", 310], [\"participant\", \"3132\"], [\"source\", nil], [\"key\", \"1721246264999-zip-contents-example\"]], \"panel_info\" => %{\"embedded?\" => false, \"panel\" => \"generic\", \"participant\" => \"3132\", \"query_string\" => %{\"entry\" => \"participate\", \"id\" => \"191\", \"participant\" => \"3132\"}}, \"remote_ip\" => \"WHOEPSIE\"})\n    (core 0.1.0) systems/storage/delivery.ex:34: Systems.Storage.Delivery.deliver/4\n    (core 0.1.0) systems/storage/delivery.ex:18: Systems.Storage.Delivery.perform/1\n    (oban 2.13.6) lib/oban/queue/executor.ex:129: Oban.Queue.Executor.perform/1\n    (oban 2.13.6) lib/oban/queue/executor.ex:74: Oban.Queue.Executor.call/1\n    (elixir 1.14.0) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2\n    (elixir 1.14.0) lib/task/supervised.ex:34: Task.Supervised.reply/4\n    (stdlib 4.0.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3\n","metadata":{"domain":["elixir"],"erl_level":"error"}}
```

**To Reproduce**
1. Donate data as participant to study backed by yoda storage

**Expected behavior**
Data is stored on yoda.

**Comment by emielvdveen** [comment]
![Image](https://github.com/user-attachments/assets/ebbee525-1651-4530-b7bc-1c45653c3baa)

**Comment by TjerkNan** [comment]
Validated as resolved
